# Generated by Django 6.1.1 on 2026-09-27 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('qr_type', models.CharField(choices=[('PERSONAL', 'Personal User QR'), ('DYNAMIC', 'Dynamic Invoice QR')], default='PERSONAL', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
