# Generated by Django 6.1.1 on 2026-09-27 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login Activity'), ('MONEY_SENT', 'Money Sent'), ('MONEY_RECEIVED', 'Money Received'), ('PAYMENT_REQUEST', 'Payment Request'), ('REQUEST_ACCEPTED', 'Payment Request Accepted'), ('REQUEST_REJECTED', 'Payment Request Rejected'), ('QR_PAYMENT', 'QR Payment'), ('ADD_MONEY', 'Wallet Top-up'), ('REFUND', 'Refund Update'), ('SECURITY_ALERT', 'Security Alert'), ('SYSTEM', 'System Announcement')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
