# Generated by Django 6.1.1 on 2026-09-27 10:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_frozen', models.BooleanField(default=False)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit (+)'), ('DEBIT', 'Debit (-)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_type', models.CharField(choices=[('ADD_MONEY', 'Add Money'), ('SEND', 'Send Money'), ('RECEIVE', 'Receive Money'), ('PAYMENT_REQUEST', 'Payment Request'), ('QR_PAYMENT', 'QR Payment'), ('WITHDRAW', 'Withdrawal'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Administrative Adjustment')], max_length=30)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Ledger Entry',
                'verbose_name_plural': 'Wallet Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallets_wal_wallet__9812f3_idx'), models.Index(fields=['reference_type', 'reference_id'], name='wallets_wal_referen_2613f7_idx')],
            },
        ),
    ]
